/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ChatSystem;

import ChatSystem.Controlleur.MainController;
import ChatSystem.Modele.Utilisateur;
import ChatSystem.Vue.MainFrame;

import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.Enumeration;
import java.util.Locale;

public class App {

    public static void main(String[] args) {
        // test détection utilisateurs
        /*int serverPort = Integer.parseInt(args[3]);
        int clientPort = Integer.parseInt(args[4]);
        String msg = args[0];
        InetAddress address = null;
        try {
            address = InetAddress.getLocalHost();
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }
        RecepteurUtilisateur recepteur = new RecepteurUtilisateur(serverPort);
        EnvoyeurUtilisateur envoyeur = new EnvoyeurUtilisateur(clientPort, address, msg);
        recepteur.start();
        envoyeur.start();*/

        // test envoi de messages
        /*InetAddress address = null;
        try {
            address = InetAddress.getLocalHost();
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }

        ConnecteurConv connecteurConv = new ConnecteurConv(Integer.parseInt(args[1]), Integer.parseInt(args[2]));
        connecteurConv.start();
        if (Integer.parseInt(args[1]) == 9000) {
            Conversation conversation = connecteurConv.connecter(address);
            GestionnaireConv.envoyerMessage("Test message", conversation);
        }*/

        // test interface graphique
        // MainFrame mainFrame = new MainFrame("test", Boolean.parseBoolean(args[0]));
        Locale.setDefault(new Locale("fr", "FR"));
        MainController mainController = new MainController(args[0],
                Integer.parseInt(args[1]),
                Integer.parseInt(args[2]),
                Integer.parseInt(args[3]),
                Integer.parseInt(args[4]),
                args[5]);
    }
}
