/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chat_system;

import chat_system.controlleur.MainController;
import org.apache.commons.cli.*;

import java.util.Locale;

/**
 * Classe principale de l'application
 */
@SuppressWarnings("ConstantConditions")
public class App {

    /**
     * Éxecute l'application
     * @param args titre_fenetre portServerTCP portClientTCP portServerUDP portClientUDP
     */
    public static void main(String[] args) {
        // langue
        Locale.setDefault(new Locale("fr", "FR"));

        Options options = new Options();

        Option title = new Option("t", "title", true, "title of the window");
        title.setOptionalArg(true);
        title.setType(String.class);

        Option tcpServer = new Option("ts", "tcpServerPort", true, "TCP server port");
        tcpServer.setOptionalArg(true);
        tcpServer.setType(Integer.class);

        Option tcpClient = new Option("tc", "tcpClientPort", true, "TCP client port");
        tcpClient.setOptionalArg(true);
        tcpClient.setType(Integer.class);

        Option udpServer = new Option("us", "udpServerPort", true, "UDP server port");
        udpServer.setOptionalArg(true);
        udpServer.setType(Integer.class);

        Option udpClient = new Option("uc", "udpServerPort", true, "UDP client port");
        udpClient.setOptionalArg(true);
        udpClient.setType(Integer.class);

        Option username = new Option("n", "username", true, "Username");
        username.setOptionalArg(true);
        username.setType(String.class);

        Option fullscreen = new Option("fs", "isFullscreen", true, "Is fullscreen");
        fullscreen.setOptionalArg(true);
        fullscreen.setType(Boolean.class);

        options.addOption(title);
        options.addOption(tcpServer);
        options.addOption(tcpClient);
        options.addOption(udpServer);
        options.addOption(udpClient);
        options.addOption(username);
        options.addOption(fullscreen);

        CommandLineParser parser = new BasicParser();

        CommandLine cmd = null;
        try {
            cmd = parser.parse(options, args);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        MainController mainController = new MainController(cmd.getOptionValue("t", "chat_system"),
                Integer.parseInt(cmd.getOptionValue("ts", "9000")),
                Integer.parseInt(cmd.getOptionValue("tc", "9000")),
                Integer.parseInt(cmd.getOptionValue("us", "9001")),
                Integer.parseInt(cmd.getOptionValue("uc", "9001")),
                cmd.getOptionValue("n", "noUsername"),
                Boolean.parseBoolean(cmd.getOptionValue("fs", "true")));
    }
}
